version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db_wm3
    restart: always
    environment:
      POSTGRES_USER: wm3
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: wm3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

